// DataPulse — Rich PPTX Export with Storytelling
import { saveAs } from 'file-saver';
import { toast } from '@/hooks/use-toast';
import { getTemplate, type TemplateId } from './reportTemplates';
import { buildReportStats, generateNarrative } from './reportNarrativeBuilder';

export async function exportRichPPTX(
  data: Record<string, unknown>[],
  datasetName: string,
  userName: string,
  title: string,
  templateId: TemplateId = 'executive',
  qualityReport?: { overallScore: number; issues: any[] } | null
) {
  try {
    const stats = buildReportStats(data, datasetName, userName, title, qualityReport);
    const tpl = getTemplate(templateId);
    const pptxgenjs = await import('pptxgenjs');
    const pptx = new pptxgenjs.default();
    pptx.layout = 'LAYOUT_WIDE';

    const pri = tpl.colors[0].replace('#', '');
    const acc = tpl.colors[1].replace('#', '');
    const txtColor = tpl.textColor.replace('#', '');
    const subColor = '999999';
    const bodyColor = '555555';

    const addNarrativeSlide = (slideTitle: string, narrative: string, opts?: { bullets?: string[]; accent?: string }) => {
      const slide = pptx.addSlide();
      slide.background = { color: 'FFFFFF' };
      // Top accent bar
      slide.addShape('rect' as any, { x: 0, y: 0, w: '100%', h: 0.08, fill: { color: acc } });
      // Title
      slide.addText(slideTitle, { x: 0.6, y: 0.3, w: '90%', fontSize: 22, bold: true, color: pri });
      // Separator
      slide.addShape('rect' as any, { x: 0.6, y: 0.75, w: 4, h: 0.03, fill: { color: acc } });
      // Narrative text
      const lines = narrative.split('\n').filter(Boolean);
      let yPos = 1.0;
      lines.forEach(line => {
        if (yPos > 4.8) return;
        slide.addText(line, { x: 0.6, y: yPos, w: '88%', fontSize: 11, color: bodyColor, lineSpacingMultiple: 1.4 });
        yPos += Math.ceil(line.length / 120) * 0.45 + 0.1;
      });
      // Bullets if provided
      if (opts?.bullets) {
        opts.bullets.forEach(b => {
          if (yPos > 5.0) return;
          slide.addText(`  •  ${b}`, { x: 0.6, y: yPos, w: '88%', fontSize: 10, color: opts.accent || bodyColor });
          yPos += 0.35;
        });
      }
      // Footer
      slide.addText(`DataPulse Analytics  |  ${stats.datasetName}  |  ${stats.date}`, { x: 0.5, y: 5.2, w: '90%', fontSize: 7, color: 'BBBBBB', align: 'center' });
    };

    // SLIDE 1 — Cover
    const cover = pptx.addSlide();
    cover.background = { color: pri };
    cover.addShape('rect' as any, { x: 0, y: 3.0, w: '100%', h: 0.06, fill: { color: acc } });
    cover.addText(stats.title, { x: 0.8, y: 1.2, w: '80%', fontSize: 34, bold: true, color: txtColor });
    cover.addText('Data Intelligence Report', { x: 0.8, y: 2.0, w: '80%', fontSize: 16, color: acc });
    cover.addText(`Comprehensive Analysis & Strategic Insights`, { x: 0.8, y: 2.5, w: '80%', fontSize: 12, color: subColor });
    cover.addText([
      `Generated by DataPulse AI  •  ${stats.date}`,
      `Dataset: ${stats.datasetName}  •  ${stats.rowCount.toLocaleString()} records  •  ${stats.columnCount} columns`,
      `Analyst: ${stats.userName}`,
      `Template: ${tpl.name}`,
    ].join('\n'), { x: 0.8, y: 3.4, w: '80%', fontSize: 10, color: subColor, lineSpacingMultiple: 1.6 });

    // SLIDE 2 — Executive Summary
    addNarrativeSlide('Executive Summary — Key Findings at a Glance', generateNarrative('executive-summary', stats, tpl.tone));

    // SLIDE 3 — Dataset Overview
    addNarrativeSlide('Understanding Your Data Landscape', generateNarrative('dataset-overview', stats, tpl.tone));

    // SLIDE 4 — KPI Dashboard
    const kpiSlide = pptx.addSlide();
    kpiSlide.background = { color: 'FFFFFF' };
    kpiSlide.addShape('rect' as any, { x: 0, y: 0, w: '100%', h: 0.08, fill: { color: acc } });
    kpiSlide.addText('Performance Metrics — Where You Stand', { x: 0.6, y: 0.3, w: '90%', fontSize: 22, bold: true, color: pri });
    kpiSlide.addShape('rect' as any, { x: 0.6, y: 0.75, w: 4, h: 0.03, fill: { color: acc } });

    const kpiNarrative = generateNarrative('kpi-analysis', stats, tpl.tone);
    kpiSlide.addText(kpiNarrative.substring(0, 300) + (kpiNarrative.length > 300 ? '...' : ''), { x: 0.6, y: 0.95, w: '88%', fontSize: 9, color: '888888', lineSpacingMultiple: 1.3 });

    stats.kpis.slice(0, 6).forEach((kpi, i) => {
      const col = i % 3;
      const row = Math.floor(i / 3);
      kpiSlide.addShape('roundRect' as any, { x: 0.5 + col * 3.3, y: 2.0 + row * 1.8, w: 3, h: 1.5, fill: { color: 'F5F5FF' }, rectRadius: 0.1, shadow: { type: 'outer', blur: 3, opacity: 0.15, offset: 2, color: '000000' } });
      kpiSlide.addText(kpi.value, { x: 0.5 + col * 3.3, y: 2.15 + row * 1.8, w: 3, fontSize: 26, bold: true, align: 'center', color: pri });
      kpiSlide.addText(kpi.label, { x: 0.5 + col * 3.3, y: 2.85 + row * 1.8, w: 3, fontSize: 10, align: 'center', color: '888888' });
    });
    kpiSlide.addText(`DataPulse Analytics  |  ${stats.datasetName}  |  ${stats.date}`, { x: 0.5, y: 5.2, w: '90%', fontSize: 7, color: 'BBBBBB', align: 'center' });

    // SLIDE 5 — Trends
    addNarrativeSlide(
      'Trend Patterns Shaping Your Data Story',
      generateNarrative('trends', stats, tpl.tone),
      { bullets: stats.trends.map(t => `${t.col}: ${t.direction} (${t.change > 0 ? '+' : ''}${t.change}%)`), accent: pri }
    );

    // SLIDE 6 — Positive Findings
    addNarrativeSlide(
      'Strengths to Leverage and Celebrate',
      generateNarrative('positives', stats, tpl.tone),
      { bullets: stats.positives.length ? stats.positives : ['All metrics stable'], accent: '22C55E' }
    );

    // SLIDE 7 — Risks & Concerns
    addNarrativeSlide(
      'Critical Issues Demanding Attention',
      generateNarrative('negatives', stats, tpl.tone),
      { bullets: stats.risks, accent: 'EF4444' }
    );

    // SLIDE 8 — Data Quality
    addNarrativeSlide(
      'Data Integrity — Foundation of Reliable Insights',
      generateNarrative('quality', stats, tpl.tone)
    );

    // SLIDE 9 — Deep Insights
    addNarrativeSlide(
      'AI-Generated Intelligence Beyond the Numbers',
      generateNarrative('deep-insights', stats, tpl.tone)
    );

    // SLIDE 10 — Recommendations
    addNarrativeSlide(
      'Strategic Action Plan — Your Next Steps',
      generateNarrative('recommendations', stats, tpl.tone),
      { bullets: stats.recommendations, accent: pri }
    );

    // SLIDE 11 — Data Table
    if (data.length > 0) {
      const tableSlide = pptx.addSlide();
      tableSlide.background = { color: 'FFFFFF' };
      tableSlide.addShape('rect' as any, { x: 0, y: 0, w: '100%', h: 0.08, fill: { color: acc } });
      tableSlide.addText('Raw Data Snapshot — Top 15 Records', { x: 0.6, y: 0.3, w: '90%', fontSize: 22, bold: true, color: pri });
      const headers = Object.keys(data[0]).slice(0, 8);
      const rows = data.slice(0, 15);
      const tableRows = [
        headers.map(h => ({ text: h.substring(0, 14), options: { bold: true, fontSize: 7, fill: { color: pri }, color: txtColor } })),
        ...rows.map(row => headers.map(h => ({ text: String(row[h] ?? '').substring(0, 16), options: { fontSize: 7, color: bodyColor } }))),
      ];
      tableSlide.addTable(tableRows as any, { x: 0.4, y: 0.9, w: 9.2, colW: Array(headers.length).fill(9.2 / headers.length), border: { pt: 0.5, color: 'DDDDDD' }, autoPage: false });
    }

    // SLIDE 12 — Closing
    const closing = pptx.addSlide();
    closing.background = { color: pri };
    closing.addText('Data Drives Decisions', { x: 1, y: 1.5, w: '80%', fontSize: 36, bold: true, align: 'center', color: txtColor });
    closing.addShape('rect' as any, { x: 3.5, y: 2.3, w: 3, h: 0.04, fill: { color: acc } });
    const topActions = stats.recommendations.slice(0, 3);
    closing.addText('Top Action Items:', { x: 1, y: 2.8, w: '80%', fontSize: 14, bold: true, align: 'center', color: acc });
    topActions.forEach((a, i) => {
      closing.addText(`${i + 1}. ${a}`, { x: 1.5, y: 3.3 + i * 0.4, w: '75%', fontSize: 11, align: 'center', color: subColor });
    });
    closing.addText(`Report generated by DataPulse AI  •  ${tpl.name} Template  •  ${stats.date}`, { x: 1, y: 4.8, w: '80%', fontSize: 9, align: 'center', color: subColor });

    const blob = await pptx.write({ outputType: 'blob' }) as Blob;
    saveAs(blob, `${stats.title.replace(/\s+/g, '-').toLowerCase()}.pptx`);
    toast({ title: 'PowerPoint Exported', description: 'Presentation downloaded successfully.' });
  } catch (e) {
    console.error('PPTX export error:', e);
    toast({ title: 'Export Failed', description: 'Could not generate PowerPoint.', variant: 'destructive' });
  }
}
