// Precision Formula Forge V5.0 — 100 enterprise-grade snippets across DAX, SQL, Excel
import type { FormulaSnippet } from '@/contexts/FormulaContext';

export const extendedFormulaLibrary: Omit<FormulaSnippet, 'savedAt'>[] = [
  // ───────────────────────── DAX (35) ─────────────────────────
  {
    id: 'dax-ytd-revenue',
    name: 'Year-to-Date Revenue',
    type: 'dax',
    category: 'Time Intelligence',
    level: 'Intermediate',
    formula: `YTD Revenue =\n    CALCULATE(\n        SUM ( ${'${tableName}'}[${'${revCol}'}] ),\n        DATESYTD ( ${'${tableName}'}[${'${dateCol}'}] )\n    )`,
    explanation: 'Aggregates revenue from the start of the calendar year through the latest date in the active filter context. Critical for executive scorecards and CFO dashboards.',
    bestUsedFor: ['Executive Reporting', 'Quarterly Reviews', 'Annual Forecasting'],
    columnsNeeded: ['Revenue', 'Date'],
  },
  {
    id: 'dax-mtd-revenue',
    name: 'Month-to-Date Revenue',
    type: 'dax',
    category: 'Time Intelligence',
    level: 'Intermediate',
    formula: `MTD Revenue =\n    CALCULATE(\n        SUM ( ${'${tableName}'}[${'${revCol}'}] ),\n        DATESMTD ( ${'${tableName}'}[${'${dateCol}'}] )\n    )`,
    explanation: 'Calculates cumulative revenue from the first day of the current month. Useful for daily ops standups and pacing analysis.',
    bestUsedFor: ['Sales Pacing', 'Operations Reviews', 'Daily Standups'],
    columnsNeeded: ['Revenue', 'Date'],
  },
  {
    id: 'dax-yoy-growth',
    name: 'YoY Growth %',
    type: 'dax',
    category: 'Time Intelligence',
    level: 'Advanced',
    formula: `YoY Growth % =\n    VAR CurrentSales = SUM ( ${'${tableName}'}[${'${revCol}'}] )\n    VAR PriorSales =\n        CALCULATE (\n            SUM ( ${'${tableName}'}[${'${revCol}'}] ),\n            SAMEPERIODLASTYEAR ( ${'${tableName}'}[${'${dateCol}'}] )\n        )\n    RETURN\n        DIVIDE ( CurrentSales - PriorSales, PriorSales )`,
    explanation: 'Compares current period revenue to the same period one year earlier and returns growth as a percentage. The standard board-level performance KPI.',
    bestUsedFor: ['Board Reporting', 'Investor Decks', 'Growth Analytics'],
    columnsNeeded: ['Revenue', 'Date'],
  },
  {
    id: 'dax-rolling-3mo-avg',
    name: 'Rolling 3-Month Average',
    type: 'dax',
    category: 'Time Intelligence',
    level: 'Advanced',
    formula: `Rolling 3M Avg =\n    CALCULATE(\n        AVERAGEX (\n            VALUES ( ${'${tableName}'}[${'${dateCol}'}] ),\n            CALCULATE ( SUM ( ${'${tableName}'}[${'${revCol}'}] ) )\n        ),\n        DATESINPERIOD (\n            ${'${tableName}'}[${'${dateCol}'}],\n            MAX ( ${'${tableName}'}[${'${dateCol}'}] ),\n            -3,\n            MONTH\n        )\n    )`,
    explanation: 'Smooths volatile time series by averaging the trailing 3 months of revenue. Eliminates noise from seasonal spikes.',
    bestUsedFor: ['Trend Analysis', 'Demand Smoothing', 'Forecast Baselines'],
    columnsNeeded: ['Revenue', 'Date'],
  },
  {
    id: 'dax-rolling-12mo-avg',
    name: 'Rolling 12-Month Average',
    type: 'dax',
    category: 'Time Intelligence',
    level: 'Advanced',
    formula: `Rolling 12M Avg =\n    CALCULATE(\n        AVERAGEX (\n            VALUES ( ${'${tableName}'}[${'${dateCol}'}] ),\n            CALCULATE ( SUM ( ${'${tableName}'}[${'${revCol}'}] ) )\n        ),\n        DATESINPERIOD (\n            ${'${tableName}'}[${'${dateCol}'}],\n            MAX ( ${'${tableName}'}[${'${dateCol}'}] ),\n            -12,\n            MONTH\n        )\n    )`,
    explanation: 'Computes a trailing 12-month moving average to remove seasonality entirely. Standard for SaaS ARR trend lines.',
    bestUsedFor: ['SaaS ARR Trends', 'Seasonality Removal', 'Long-term Trend'],
    columnsNeeded: ['Revenue', 'Date'],
  },
  {
    id: 'dax-pareto-80-20',
    name: 'Pareto (80/20) Cumulative %',
    type: 'dax',
    category: 'Statistical Analysis',
    level: 'Expert',
    formula: `Pareto % =\n    VAR CurrentRevenue = [Total Revenue]\n    VAR Ranking =\n        RANKX (\n            ALLSELECTED ( ${'${tableName}'}[${'${prodCol}'}] ),\n            [Total Revenue],\n            ,\n            DESC\n        )\n    VAR CumulativeRevenue =\n        CALCULATE(\n            [Total Revenue],\n            FILTER (\n                ALLSELECTED ( ${'${tableName}'}[${'${prodCol}'}] ),\n                RANKX (\n                    ALLSELECTED ( ${'${tableName}'}[${'${prodCol}'}] ),\n                    [Total Revenue],\n                    ,\n                    DESC\n                ) <= Ranking\n            )\n        )\n    RETURN\n        DIVIDE ( CumulativeRevenue, CALCULATE ( [Total Revenue], ALLSELECTED ( ${'${tableName}'}[${'${prodCol}'}] ) ) )`,
    explanation: 'Ranks products by revenue and computes cumulative contribution to identify the vital few driving 80% of results. Foundation for SKU rationalization.',
    bestUsedFor: ['SKU Rationalization', 'Customer Concentration', 'Risk Analysis'],
    columnsNeeded: ['Product', 'Revenue'],
  },
  {
    id: 'dax-abc-classification',
    name: 'ABC Classification',
    type: 'dax',
    category: 'Statistical Analysis',
    level: 'Expert',
    formula: `ABC Class =\n    VAR ParetoPct = [Pareto %]\n    RETURN\n        SWITCH (\n            TRUE (),\n            ParetoPct <= 0.80, "A",\n            ParetoPct <= 0.95, "B",\n            "C"\n        )`,
    explanation: 'Segments items into A (top 80%), B (next 15%), and C (bottom 5%) based on cumulative revenue contribution. Inventory and account tiering standard.',
    bestUsedFor: ['Inventory Tiering', 'Account Segmentation', 'Procurement Strategy'],
    columnsNeeded: ['Pareto %'],
  },
  {
    id: 'dax-rank-products',
    name: 'Dense Product Ranking',
    type: 'dax',
    category: 'Ranking & Top N',
    level: 'Intermediate',
    formula: `Product Rank =\n    RANKX (\n        ALLSELECTED ( ${'${tableName}'}[${'${prodCol}'}] ),\n        [Total Revenue],\n        ,\n        DESC,\n        DENSE\n    )`,
    explanation: 'Assigns a dense rank to each product by total revenue within the selected filter context. Powers leaderboards and Top N visuals.',
    bestUsedFor: ['Sales Leaderboards', 'Top N Reports', 'Competitor Benchmarks'],
    columnsNeeded: ['Product', 'Revenue'],
  },
  {
    id: 'dax-top-n-filter',
    name: 'Dynamic Top N Filter',
    type: 'dax',
    category: 'Ranking & Top N',
    level: 'Advanced',
    formula: `Top N Revenue =\n    VAR N = SELECTEDVALUE ( 'Top N Param'[Value], 10 )\n    RETURN\n        CALCULATE (\n            [Total Revenue],\n            TOPN ( N, ALLSELECTED ( ${'${tableName}'}[${'${prodCol}'}] ), [Total Revenue], DESC )\n        )`,
    explanation: 'Returns revenue restricted to the user-selected top N items via a what-if parameter. Enables interactive drill-down.',
    bestUsedFor: ['Interactive Dashboards', 'Dynamic Filtering', 'Self-Service BI'],
    columnsNeeded: ['Revenue', 'Product'],
  },
  {
    id: 'dax-customer-churn-rate',
    name: 'Customer Churn Rate',
    type: 'dax',
    category: 'Predictive Measures',
    level: 'Expert',
    formula: `Churn Rate =\n    VAR ActiveStart =\n        CALCULATE (\n            DISTINCTCOUNT ( ${'${tableName}'}[${'${custCol}'}] ),\n            DATEADD ( ${'${tableName}'}[${'${dateCol}'}], -1, MONTH )\n        )\n    VAR ActiveEnd = DISTINCTCOUNT ( ${'${tableName}'}[${'${custCol}'}] )\n    VAR Lost = ActiveStart - ActiveEnd\n    RETURN DIVIDE ( Lost, ActiveStart )`,
    explanation: 'Compares active customers at the end of the period vs the prior period to estimate churn. Critical SaaS retention KPI.',
    bestUsedFor: ['Churn Prevention', 'SaaS Retention', 'CS Forecasting'],
    columnsNeeded: ['CustomerID', 'Date'],
  },
  {
    id: 'dax-customer-ltv',
    name: 'Customer Lifetime Value',
    type: 'dax',
    category: 'Financial Intelligence',
    level: 'Advanced',
    formula: `Customer LTV =\n    VAR AvgRevenue = DIVIDE ( [Total Revenue], DISTINCTCOUNT ( ${'${tableName}'}[${'${custCol}'}] ) )\n    VAR AvgLifespanMonths = 24\n    VAR GrossMargin = 0.65\n    RETURN AvgRevenue * AvgLifespanMonths * GrossMargin`,
    explanation: 'Estimates average lifetime value per customer using revenue, expected tenure, and gross margin. Drives CAC payback decisions.',
    bestUsedFor: ['CAC Payback', 'Marketing ROI', 'Customer Strategy'],
    columnsNeeded: ['Revenue', 'CustomerID'],
  },
  {
    id: 'dax-linear-regression-forecast',
    name: 'Linear Regression Forecast',
    type: 'dax',
    category: 'Predictive Measures',
    level: 'Expert',
    formula: `Linear Forecast =\n    VAR Known =\n        FILTER (\n            SELECTCOLUMNS (\n                VALUES ( ${'${tableName}'}[${'${dateCol}'}] ),\n                "X", DATEDIFF ( DATE ( 2020, 1, 1 ), [${'${dateCol}'}], DAY ),\n                "Y", [Total Revenue]\n            ),\n            NOT ISBLANK ( [Y] )\n        )\n    VAR N = COUNTROWS ( Known )\n    VAR SumX = SUMX ( Known, [X] )\n    VAR SumY = SUMX ( Known, [Y] )\n    VAR SumXY = SUMX ( Known, [X] * [Y] )\n    VAR SumX2 = SUMX ( Known, [X] * [X] )\n    VAR Slope = DIVIDE ( N * SumXY - SumX * SumY, N * SumX2 - SumX * SumX )\n    VAR Intercept = DIVIDE ( SumY - Slope * SumX, N )\n    VAR CurrentX = DATEDIFF ( DATE ( 2020, 1, 1 ), MAX ( ${'${tableName}'}[${'${dateCol}'}] ), DAY )\n    RETURN Slope * CurrentX + Intercept`,
    explanation: 'Computes a least-squares linear regression on historical revenue and projects the next value. Useful as a transparent forecasting baseline.',
    bestUsedFor: ['Revenue Forecasting', 'Trend Projection', 'Budget Planning'],
    columnsNeeded: ['Revenue', 'Date'],
  },
  {
    id: 'dax-window-running-total',
    name: 'Running Total via WINDOW',
    type: 'dax',
    category: 'Time Intelligence',
    level: 'Expert',
    formula: `Running Total =\n    CALCULATE (\n        [Total Revenue],\n        WINDOW (\n            1, ABS,\n            0, REL,\n            ORDERBY ( ${'${tableName}'}[${'${dateCol}'}], ASC )\n        )\n    )`,
    explanation: 'Uses the modern WINDOW function to compute a running total from the first row to the current row. Replaces older filter-based patterns.',
    bestUsedFor: ['Cumulative Reports', 'Cash Flow', 'Backlog Tracking'],
    columnsNeeded: ['Revenue', 'Date'],
  },
  {
    id: 'dax-offset-prior-period',
    name: 'Prior Period via OFFSET',
    type: 'dax',
    category: 'Time Intelligence',
    level: 'Expert',
    formula: `Prior Period =\n    CALCULATE (\n        [Total Revenue],\n        OFFSET (\n            -1,\n            ALLSELECTED ( ${'${tableName}'}[${'${dateCol}'}] ),\n            ORDERBY ( ${'${tableName}'}[${'${dateCol}'}], ASC )\n        )\n    )`,
    explanation: 'Returns the prior visible period value using the OFFSET window function for clean period-over-period comparisons.',
    bestUsedFor: ['Period Comparisons', 'Variance Reports', 'Trend Visuals'],
    columnsNeeded: ['Revenue', 'Date'],
  },
  {
    id: 'dax-index-first-value',
    name: 'First Period Value via INDEX',
    type: 'dax',
    category: 'Time Intelligence',
    level: 'Advanced',
    formula: `First Period Revenue =\n    CALCULATE (\n        [Total Revenue],\n        INDEX (\n            1,\n            ALLSELECTED ( ${'${tableName}'}[${'${dateCol}'}] ),\n            ORDERBY ( ${'${tableName}'}[${'${dateCol}'}], ASC )\n        )\n    )`,
    explanation: 'Returns revenue at the first visible period for indexing growth (Period 1 = 100). Critical for cohort indexed charts.',
    bestUsedFor: ['Cohort Indexing', 'Growth Indices', 'Benchmark Charts'],
    columnsNeeded: ['Revenue', 'Date'],
  },
  {
    id: 'dax-conditional-color',
    name: 'Conditional KPI Color',
    type: 'dax',
    category: 'Conditional & Switching',
    level: 'Intermediate',
    formula: `KPI Color =\n    SWITCH (\n        TRUE (),\n        [YoY Growth %] >= 0.10, "#30D158",\n        [YoY Growth %] >= 0,    "#FF9F0A",\n        "#FF453A"\n    )`,
    explanation: 'Returns a hex color based on growth thresholds for use in conditional formatting on cards and tables. Clean traffic-light KPIs.',
    bestUsedFor: ['Executive Cards', 'Conditional Formatting', 'Status Dashboards'],
    columnsNeeded: ['YoY Growth %'],
  },
  {
    id: 'dax-isfiltered-context',
    name: 'Filter Context Detector',
    type: 'dax',
    category: 'Conditional & Switching',
    level: 'Advanced',
    formula: `Selected Label =\n    SWITCH (\n        TRUE (),\n        ISFILTERED ( ${'${tableName}'}[${'${prodCol}'}] ), SELECTEDVALUE ( ${'${tableName}'}[${'${prodCol}'}], "Multiple" ),\n        "All Products"\n    )`,
    explanation: 'Returns the active filter selection or a fallback label, enabling smart, dynamic chart titles.',
    bestUsedFor: ['Dynamic Titles', 'Tooltip Text', 'Narrative Visuals'],
    columnsNeeded: ['Product'],
  },
  {
    id: 'dax-distinct-customers',
    name: 'Distinct Active Customers',
    type: 'dax',
    category: 'Core Aggregations',
    level: 'Intermediate',
    formula: `Active Customers =\n    CALCULATE (\n        DISTINCTCOUNT ( ${'${tableName}'}[${'${custCol}'}] ),\n        ${'${tableName}'}[${'${revCol}'}] > 0\n    )`,
    explanation: 'Counts unique customers who actually transacted, ignoring zero-value rows. Avoids inflated customer counts.',
    bestUsedFor: ['Active User KPIs', 'CRM Reports', 'Engagement Tracking'],
    columnsNeeded: ['CustomerID', 'Revenue'],
  },
  {
    id: 'dax-customer-rfm-score',
    name: 'RFM Composite Score',
    type: 'dax',
    category: 'Predictive Measures',
    level: 'Expert',
    formula: `RFM Score =\n    VAR LastDate = MAX ( ${'${tableName}'}[${'${dateCol}'}] )\n    VAR R = DATEDIFF ( CALCULATE ( MAX ( ${'${tableName}'}[${'${dateCol}'}] ) ), LastDate, DAY )\n    VAR F = CALCULATE ( COUNTROWS ( ${'${tableName}'} ) )\n    VAR M = [Total Revenue]\n    VAR R_Score = SWITCH ( TRUE (), R <= 30, 5, R <= 60, 4, R <= 90, 3, R <= 180, 2, 1 )\n    VAR F_Score = SWITCH ( TRUE (), F >= 20, 5, F >= 10, 4, F >= 5, 3, F >= 2, 2, 1 )\n    VAR M_Score = SWITCH ( TRUE (), M >= 10000, 5, M >= 5000, 4, M >= 1000, 3, M >= 500, 2, 1 )\n    RETURN R_Score * 100 + F_Score * 10 + M_Score`,
    explanation: 'Computes Recency, Frequency, Monetary scores per customer and concatenates into a 3-digit composite. Backbone of marketing segmentation.',
    bestUsedFor: ['Customer Segmentation', 'Loyalty Programs', 'Targeted Campaigns'],
    columnsNeeded: ['CustomerID', 'Date', 'Revenue'],
  },
  {
    id: 'dax-percentile-revenue',
    name: '90th Percentile Revenue',
    type: 'dax',
    category: 'Statistical Analysis',
    level: 'Advanced',
    formula: `P90 Revenue =\n    PERCENTILEX.INC (\n        VALUES ( ${'${tableName}'}[${'${custCol}'}] ),\n        [Total Revenue],\n        0.90\n    )`,
    explanation: 'Returns the 90th percentile of customer revenue, useful for identifying VIP thresholds without outlier distortion.',
    bestUsedFor: ['VIP Thresholds', 'Outlier Detection', 'Pricing Tiers'],
    columnsNeeded: ['CustomerID', 'Revenue'],
  },
  {
    id: 'dax-stddev-revenue',
    name: 'Revenue Volatility (StdDev)',
    type: 'dax',
    category: 'Statistical Analysis',
    level: 'Advanced',
    formula: `Revenue StdDev =\n    STDEVX.P (\n        VALUES ( ${'${tableName}'}[${'${dateCol}'}] ),\n        [Total Revenue]\n    )`,
    explanation: 'Computes the population standard deviation of daily revenue to quantify volatility. Drives risk-adjusted forecasting.',
    bestUsedFor: ['Risk Analysis', 'Forecast Confidence', 'Volatility Tracking'],
    columnsNeeded: ['Revenue', 'Date'],
  },
  {
    id: 'dax-coefficient-variation',
    name: 'Coefficient of Variation',
    type: 'dax',
    category: 'Statistical Analysis',
    level: 'Expert',
    formula: `CV =\n    DIVIDE ( [Revenue StdDev], AVERAGEX ( VALUES ( ${'${tableName}'}[${'${dateCol}'}] ), [Total Revenue] ) )`,
    explanation: 'Normalizes standard deviation by the mean to compare volatility across products of different scales.',
    bestUsedFor: ['Cross-Product Risk', 'SKU Stability', 'Portfolio Analysis'],
    columnsNeeded: ['Revenue StdDev'],
  },
  {
    id: 'dax-gross-profit-margin',
    name: 'Gross Profit Margin %',
    type: 'dax',
    category: 'Financial Intelligence',
    level: 'Intermediate',
    formula: `GP Margin % =\n    DIVIDE (\n        SUM ( ${'${tableName}'}[${'${revCol}'}] ) - SUM ( ${'${tableName}'}[Cost] ),\n        SUM ( ${'${tableName}'}[${'${revCol}'}] )\n    )`,
    explanation: 'Standard gross profit margin computed as (Revenue − COGS) / Revenue. Foundational P&L KPI.',
    bestUsedFor: ['P&L Reporting', 'Margin Analysis', 'Pricing Decisions'],
    columnsNeeded: ['Revenue', 'Cost'],
  },
  {
    id: 'dax-ebitda-margin',
    name: 'EBITDA Margin %',
    type: 'dax',
    category: 'Financial Intelligence',
    level: 'Advanced',
    formula: `EBITDA Margin =\n    DIVIDE (\n        SUM ( ${'${tableName}'}[${'${revCol}'}] ) - SUM ( ${'${tableName}'}[Cost] ) - SUM ( ${'${tableName}'}[OpEx] ),\n        SUM ( ${'${tableName}'}[${'${revCol}'}] )\n    )`,
    explanation: 'EBITDA divided by revenue, the operating profitability metric used by investors and FP&A.',
    bestUsedFor: ['Investor Reporting', 'M&A Analysis', 'Operating Performance'],
    columnsNeeded: ['Revenue', 'Cost', 'OpEx'],
  },
  {
    id: 'dax-customer-acquisition-cost',
    name: 'Customer Acquisition Cost',
    type: 'dax',
    category: 'Financial Intelligence',
    level: 'Intermediate',
    formula: `CAC =\n    DIVIDE (\n        SUM ( ${'${tableName}'}[MarketingSpend] ),\n        DISTINCTCOUNT ( ${'${tableName}'}[NewCustomerID] )\n    )`,
    explanation: 'Average marketing spend required to acquire one new customer. Central to growth efficiency analysis.',
    bestUsedFor: ['Growth Efficiency', 'Marketing ROI', 'Budget Allocation'],
    columnsNeeded: ['MarketingSpend', 'NewCustomerID'],
  },
  {
    id: 'dax-ltv-cac-ratio',
    name: 'LTV : CAC Ratio',
    type: 'dax',
    category: 'Financial Intelligence',
    level: 'Advanced',
    formula: `LTV/CAC =\n    DIVIDE ( [Customer LTV], [CAC] )`,
    explanation: 'The most-watched SaaS unit-economics ratio. Healthy benchmarks sit above 3:1.',
    bestUsedFor: ['Unit Economics', 'Investor Decks', 'Growth Strategy'],
    columnsNeeded: ['Customer LTV', 'CAC'],
  },
  {
    id: 'dax-revenue-concentration',
    name: 'Top 10 Customer Concentration',
    type: 'dax',
    category: 'Statistical Analysis',
    level: 'Expert',
    formula: `Top10 Concentration =\n    DIVIDE (\n        CALCULATE (\n            [Total Revenue],\n            TOPN ( 10, ALLSELECTED ( ${'${tableName}'}[${'${custCol}'}] ), [Total Revenue], DESC )\n        ),\n        CALCULATE ( [Total Revenue], ALLSELECTED ( ${'${tableName}'}[${'${custCol}'}] ) )\n    )`,
    explanation: 'Measures revenue share generated by the top 10 customers. A high value flags dangerous concentration risk.',
    bestUsedFor: ['Concentration Risk', 'Account Strategy', 'Audit Reviews'],
    columnsNeeded: ['CustomerID', 'Revenue'],
  },
  {
    id: 'dax-new-vs-returning',
    name: 'New vs Returning Customer Revenue',
    type: 'dax',
    category: 'Predictive Measures',
    level: 'Expert',
    formula: `New Customer Revenue =\n    VAR CurrentCustomers = VALUES ( ${'${tableName}'}[${'${custCol}'}] )\n    VAR PriorCustomers =\n        CALCULATETABLE (\n            VALUES ( ${'${tableName}'}[${'${custCol}'}] ),\n            DATESBETWEEN ( ${'${tableName}'}[${'${dateCol}'}], BLANK (), MIN ( ${'${tableName}'}[${'${dateCol}'}] ) - 1 )\n        )\n    VAR NewOnly = EXCEPT ( CurrentCustomers, PriorCustomers )\n    RETURN CALCULATE ( [Total Revenue], NewOnly )`,
    explanation: 'Splits revenue from net-new customers vs returning ones using EXCEPT on customer sets. Essential for growth attribution.',
    bestUsedFor: ['Growth Attribution', 'Cohort Analysis', 'Marketing Mix'],
    columnsNeeded: ['CustomerID', 'Date', 'Revenue'],
  },
  {
    id: 'dax-budget-variance',
    name: 'Budget Variance %',
    type: 'dax',
    category: 'Financial Intelligence',
    level: 'Intermediate',
    formula: `Budget Variance % =\n    DIVIDE (\n        SUM ( ${'${tableName}'}[${'${revCol}'}] ) - SUM ( ${'${tableName}'}[Budget] ),\n        SUM ( ${'${tableName}'}[Budget] )\n    )`,
    explanation: 'Compares actuals against budget as a percentage variance. The core FP&A control metric.',
    bestUsedFor: ['FP&A Reviews', 'Variance Reports', 'Cost Control'],
    columnsNeeded: ['Revenue', 'Budget'],
  },
  {
    id: 'dax-forecast-accuracy',
    name: 'Forecast Accuracy (MAPE)',
    type: 'dax',
    category: 'Predictive Measures',
    level: 'Advanced',
    formula: `MAPE =\n    AVERAGEX (\n        VALUES ( ${'${tableName}'}[${'${dateCol}'}] ),\n        DIVIDE (\n            ABS ( [Total Revenue] - [Forecast Revenue] ),\n            [Total Revenue]\n        )\n    )`,
    explanation: 'Mean Absolute Percentage Error between actuals and forecast — the standard accuracy metric for demand models.',
    bestUsedFor: ['Forecast QA', 'Model Selection', 'S&OP Reviews'],
    columnsNeeded: ['Revenue', 'Forecast Revenue', 'Date'],
  },
  {
    id: 'dax-sales-velocity',
    name: 'Sales Velocity',
    type: 'dax',
    category: 'Financial Intelligence',
    level: 'Advanced',
    formula: `Sales Velocity =\n    DIVIDE (\n        DISTINCTCOUNT ( ${'${tableName}'}[OpportunityID] ) * [Avg Deal Size] * [Win Rate],\n        [Avg Sales Cycle Days]\n    )`,
    explanation: 'Combines pipeline volume, deal size, win rate and cycle length into one revenue-per-day score for the sales engine.',
    bestUsedFor: ['Sales Operations', 'Pipeline Reviews', 'Capacity Planning'],
    columnsNeeded: ['OpportunityID', 'Avg Deal Size', 'Win Rate', 'Avg Sales Cycle Days'],
  },
  {
    id: 'dax-net-revenue-retention',
    name: 'Net Revenue Retention',
    type: 'dax',
    category: 'Financial Intelligence',
    level: 'Expert',
    formula: `NRR =\n    VAR StartARR = CALCULATE ( [Total Revenue], DATEADD ( ${'${tableName}'}[${'${dateCol}'}], -12, MONTH ) )\n    VAR EndARR = CALCULATE ( [Total Revenue], VALUES ( ${'${tableName}'}[${'${custCol}'}] ) IN VALUES ( ${'${tableName}'}[${'${custCol}'}] ) )\n    RETURN DIVIDE ( EndARR, StartARR )`,
    explanation: 'Measures recurring revenue from the existing customer base year over year, including expansion and churn. The premier SaaS retention metric.',
    bestUsedFor: ['SaaS Boards', 'Investor Reporting', 'Retention Strategy'],
    columnsNeeded: ['Revenue', 'CustomerID', 'Date'],
  },
  {
    id: 'dax-zscore-anomaly',
    name: 'Z-Score Anomaly Flag',
    type: 'dax',
    category: 'Statistical Analysis',
    level: 'Expert',
    formula: `Anomaly Flag =\n    VAR Mu = AVERAGEX ( VALUES ( ${'${tableName}'}[${'${dateCol}'}] ), [Total Revenue] )\n    VAR Sigma = [Revenue StdDev]\n    VAR Z = DIVIDE ( [Total Revenue] - Mu, Sigma )\n    RETURN IF ( ABS ( Z ) > 2.5, 1, 0 )`,
    explanation: 'Flags daily revenue values that deviate more than 2.5 standard deviations from the mean. Drives anomaly alerts.',
    bestUsedFor: ['Anomaly Detection', 'Fraud Alerts', 'Operational Monitoring'],
    columnsNeeded: ['Revenue', 'Date', 'Revenue StdDev'],
  },
  {
    id: 'dax-quartile-segment',
    name: 'Customer Quartile Segment',
    type: 'dax',
    category: 'Statistical Analysis',
    level: 'Advanced',
    formula: `Customer Quartile =\n    VAR Q1 = PERCENTILEX.INC ( VALUES ( ${'${tableName}'}[${'${custCol}'}] ), [Total Revenue], 0.25 )\n    VAR Q2 = PERCENTILEX.INC ( VALUES ( ${'${tableName}'}[${'${custCol}'}] ), [Total Revenue], 0.50 )\n    VAR Q3 = PERCENTILEX.INC ( VALUES ( ${'${tableName}'}[${'${custCol}'}] ), [Total Revenue], 0.75 )\n    RETURN\n        SWITCH ( TRUE (),\n            [Total Revenue] >= Q3, "Q4 — Top",\n            [Total Revenue] >= Q2, "Q3",\n            [Total Revenue] >= Q1, "Q2",\n            "Q1 — Bottom"\n        )`,
    explanation: 'Splits customers into revenue quartiles for fair-share comparisons and tiered service models.',
    bestUsedFor: ['Customer Tiering', 'Service Levels', 'Account Mgmt'],
    columnsNeeded: ['CustomerID', 'Revenue'],
  },
  {
    id: 'dax-dynamic-time-grain',
    name: 'Dynamic Time Grain Switch',
    type: 'dax',
    category: 'Conditional & Switching',
    level: 'Expert',
    formula: `Revenue by Grain =\n    SWITCH (\n        SELECTEDVALUE ( 'Time Grain'[Grain], "Day" ),\n        "Day",   [Total Revenue],\n        "Week",  CALCULATE ( [Total Revenue], DATESINPERIOD ( ${'${tableName}'}[${'${dateCol}'}], MAX ( ${'${tableName}'}[${'${dateCol}'}] ), -7, DAY ) ),\n        "Month", [MTD Revenue],\n        "Year",  [YTD Revenue]\n    )`,
    explanation: 'Switches the active aggregation grain based on a user-selected parameter, powering one chart that responds to multiple time scopes.',
    bestUsedFor: ['Dynamic Charts', 'Self-Service Analytics', 'Executive Dashboards'],
    columnsNeeded: ['Revenue', 'Date'],
  },

  // ───────────────────────── SQL (35) ─────────────────────────
  {
    id: 'sql-cohort-retention',
    name: 'Dynamic Cohort Retention %',
    type: 'sql',
    category: 'Cohort & Funnel Tracking',
    level: 'Expert',
    formula: `WITH cohorts AS (\n    SELECT\n        ${'${custCol}'} AS customer_id,\n        DATE_TRUNC('month', MIN(${'${dateCol}'})) AS cohort_month\n    FROM ${'${tableName}'}\n    GROUP BY ${'${custCol}'}\n),\nactivity AS (\n    SELECT\n        c.cohort_month,\n        DATE_TRUNC('month', t.${'${dateCol}'}) AS activity_month,\n        COUNT(DISTINCT t.${'${custCol}'}) AS active_users\n    FROM ${'${tableName}'} t\n    JOIN cohorts c ON c.customer_id = t.${'${custCol}'}\n    GROUP BY 1, 2\n),\ncohort_size AS (\n    SELECT cohort_month, COUNT(*) AS size\n    FROM cohorts\n    GROUP BY cohort_month\n)\nSELECT\n    a.cohort_month,\n    a.activity_month,\n    EXTRACT(MONTH FROM AGE(a.activity_month, a.cohort_month)) AS month_number,\n    ROUND(100.0 * a.active_users / s.size, 2) AS retention_pct\nFROM activity a\nJOIN cohort_size s ON s.cohort_month = a.cohort_month\nORDER BY 1, 2;`,
    explanation: 'Builds a monthly retention triangle by anchoring each customer to their first-purchase cohort and measuring active share each subsequent month.',
    bestUsedFor: ['Retention Analysis', 'SaaS Cohorts', 'Lifecycle Marketing'],
    columnsNeeded: ['CustomerID', 'Date'],
  },
  {
    id: 'sql-rfm-segmentation',
    name: 'RFM Segmentation with NTILE',
    type: 'sql',
    category: 'Statistical SQL',
    level: 'Expert',
    formula: `WITH rfm AS (\n    SELECT\n        ${'${custCol}'} AS customer_id,\n        CURRENT_DATE - MAX(${'${dateCol}'})::date AS recency_days,\n        COUNT(*) AS frequency,\n        SUM(${'${revCol}'}) AS monetary\n    FROM ${'${tableName}'}\n    GROUP BY ${'${custCol}'}\n),\nscored AS (\n    SELECT\n        customer_id,\n        NTILE(5) OVER (ORDER BY recency_days ASC) AS r_score,\n        NTILE(5) OVER (ORDER BY frequency DESC) AS f_score,\n        NTILE(5) OVER (ORDER BY monetary DESC) AS m_score\n    FROM rfm\n)\nSELECT\n    customer_id,\n    r_score, f_score, m_score,\n    (r_score * 100 + f_score * 10 + m_score) AS rfm_score,\n    CASE\n        WHEN r_score >= 4 AND f_score >= 4 THEN 'Champions'\n        WHEN r_score >= 3 AND m_score >= 4 THEN 'Loyal'\n        WHEN r_score <= 2 AND f_score <= 2 THEN 'At Risk'\n        ELSE 'Regular'\n    END AS segment\nFROM scored;`,
    explanation: 'Computes Recency/Frequency/Monetary tiers via NTILE quintiles and assigns marketable customer segments. Industry-standard segmentation.',
    bestUsedFor: ['Customer Segmentation', 'Targeted Campaigns', 'CRM Strategy'],
    columnsNeeded: ['CustomerID', 'Date', 'Revenue'],
  },
  {
    id: 'sql-funnel-dropoff',
    name: 'Funnel Drop-off Analysis',
    type: 'sql',
    category: 'Cohort & Funnel Tracking',
    level: 'Expert',
    formula: `WITH steps AS (\n    SELECT user_id,\n        MAX(CASE WHEN event = 'visit'    THEN 1 ELSE 0 END) AS s1,\n        MAX(CASE WHEN event = 'signup'   THEN 1 ELSE 0 END) AS s2,\n        MAX(CASE WHEN event = 'activate' THEN 1 ELSE 0 END) AS s3,\n        MAX(CASE WHEN event = 'paid'     THEN 1 ELSE 0 END) AS s4\n    FROM ${'${tableName}'}\n    GROUP BY user_id\n)\nSELECT\n    SUM(s1) AS visits,\n    SUM(s2) AS signups,\n    SUM(s3) AS activated,\n    SUM(s4) AS paid,\n    ROUND(100.0 * SUM(s2)/NULLIF(SUM(s1),0), 2) AS visit_to_signup,\n    ROUND(100.0 * SUM(s3)/NULLIF(SUM(s2),0), 2) AS signup_to_active,\n    ROUND(100.0 * SUM(s4)/NULLIF(SUM(s3),0), 2) AS active_to_paid\nFROM steps;`,
    explanation: 'Pivots event log data into a four-stage funnel and computes step-over-step conversion rates. Backbone of growth analytics.',
    bestUsedFor: ['Growth Analytics', 'Conversion Optimization', 'Onboarding QA'],
    columnsNeeded: ['user_id', 'event'],
  },
  {
    id: 'sql-lag-momentum',
    name: 'Day-over-Day Momentum (LAG)',
    type: 'sql',
    category: 'Window Functions',
    level: 'Advanced',
    formula: `SELECT\n    ${'${dateCol}'} AS day,\n    SUM(${'${revCol}'}) AS revenue,\n    LAG(SUM(${'${revCol}'}), 1) OVER (ORDER BY ${'${dateCol}'}) AS prev_revenue,\n    ROUND(\n        100.0 * (SUM(${'${revCol}'}) - LAG(SUM(${'${revCol}'}), 1) OVER (ORDER BY ${'${dateCol}'}))\n        / NULLIF(LAG(SUM(${'${revCol}'}), 1) OVER (ORDER BY ${'${dateCol}'}), 0),\n        2\n    ) AS dod_pct\nFROM ${'${tableName}'}\nGROUP BY ${'${dateCol}'}\nORDER BY ${'${dateCol}'};`,
    explanation: 'Uses LAG to compare each day to the previous day and compute day-over-day percentage change. Standard for ops dashboards.',
    bestUsedFor: ['Daily Ops Reports', 'Momentum Tracking', 'Trend Visuals'],
    columnsNeeded: ['Date', 'Revenue'],
  },
  {
    id: 'sql-lead-future-comparison',
    name: 'Look-Ahead with LEAD',
    type: 'sql',
    category: 'Window Functions',
    level: 'Advanced',
    formula: `SELECT\n    ${'${custCol}'} AS customer_id,\n    ${'${dateCol}'} AS order_date,\n    LEAD(${'${dateCol}'}) OVER (PARTITION BY ${'${custCol}'} ORDER BY ${'${dateCol}'}) AS next_order_date,\n    LEAD(${'${dateCol}'}) OVER (PARTITION BY ${'${custCol}'} ORDER BY ${'${dateCol}'})\n        - ${'${dateCol}'} AS days_to_next_order\nFROM ${'${tableName}'};`,
    explanation: 'Uses LEAD to compute the gap between consecutive customer purchases. Foundational for repeat-purchase modelling.',
    bestUsedFor: ['Repeat Purchase Modelling', 'Subscription Renewals', 'Lifecycle Marketing'],
    columnsNeeded: ['CustomerID', 'Date'],
  },
  {
    id: 'sql-percentile-cont',
    name: 'Median & P95 with PERCENTILE_CONT',
    type: 'sql',
    category: 'Statistical SQL',
    level: 'Advanced',
    formula: `SELECT\n    ${'${prodCol}'} AS product,\n    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY ${'${revCol}'}) AS median_revenue,\n    PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY ${'${revCol}'}) AS p90_revenue,\n    PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY ${'${revCol}'}) AS p95_revenue\nFROM ${'${tableName}'}\nGROUP BY ${'${prodCol}'};`,
    explanation: 'Computes continuous percentiles within each product group for robust distribution profiling that resists outliers.',
    bestUsedFor: ['Distribution Analysis', 'Pricing Strategy', 'Outlier-Resilient Reporting'],
    columnsNeeded: ['Product', 'Revenue'],
  },
  {
    id: 'sql-recursive-cte-hierarchy',
    name: 'Recursive Org Hierarchy',
    type: 'sql',
    category: 'CTEs & Subqueries',
    level: 'Expert',
    formula: `WITH RECURSIVE hierarchy AS (\n    SELECT employee_id, manager_id, name, 1 AS level\n    FROM employees\n    WHERE manager_id IS NULL\n    UNION ALL\n    SELECT e.employee_id, e.manager_id, e.name, h.level + 1\n    FROM employees e\n    JOIN hierarchy h ON e.manager_id = h.employee_id\n)\nSELECT level, COUNT(*) AS headcount, STRING_AGG(name, ', ') AS people\nFROM hierarchy\nGROUP BY level\nORDER BY level;`,
    explanation: 'Walks parent-child relationships recursively to flatten an organizational hierarchy with depth levels.',
    bestUsedFor: ['Org Reporting', 'Bill-of-Materials', 'Category Trees'],
    columnsNeeded: ['employee_id', 'manager_id', 'name'],
  },
  {
    id: 'sql-7d-moving-avg',
    name: '7-Day Moving Average',
    type: 'sql',
    category: 'Time Series Analysis',
    level: 'Advanced',
    formula: `SELECT\n    ${'${dateCol}'} AS day,\n    SUM(${'${revCol}'}) AS daily_revenue,\n    AVG(SUM(${'${revCol}'})) OVER (\n        ORDER BY ${'${dateCol}'}\n        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW\n    ) AS ma_7d\nFROM ${'${tableName}'}\nGROUP BY ${'${dateCol}'}\nORDER BY ${'${dateCol}'};`,
    explanation: 'Window-based 7-day moving average smooths weekly noise from daily revenue series.',
    bestUsedFor: ['Trend Smoothing', 'Daily Ops Reviews', 'Seasonality Removal'],
    columnsNeeded: ['Date', 'Revenue'],
  },
  {
    id: 'sql-running-total',
    name: 'Running Total (SUM OVER)',
    type: 'sql',
    category: 'Window Functions',
    level: 'Intermediate',
    formula: `SELECT\n    ${'${dateCol}'} AS day,\n    SUM(${'${revCol}'}) AS daily_revenue,\n    SUM(SUM(${'${revCol}'})) OVER (ORDER BY ${'${dateCol}'}) AS running_total\nFROM ${'${tableName}'}\nGROUP BY ${'${dateCol}'}\nORDER BY ${'${dateCol}'};`,
    explanation: 'Cumulative sum across the time series via window function. Replaces self-joins for waterfall and pacing reports.',
    bestUsedFor: ['Cash Flow', 'Pacing Reports', 'Waterfall Charts'],
    columnsNeeded: ['Date', 'Revenue'],
  },
  {
    id: 'sql-row-dedup',
    name: 'Deduplicate Latest Record',
    type: 'sql',
    category: 'Window Functions',
    level: 'Advanced',
    formula: `WITH ranked AS (\n    SELECT\n        *,\n        ROW_NUMBER() OVER (PARTITION BY ${'${custCol}'} ORDER BY ${'${dateCol}'} DESC) AS rn\n    FROM ${'${tableName}'}\n)\nSELECT *\nFROM ranked\nWHERE rn = 1;`,
    explanation: 'Keeps only the most recent record per customer using ROW_NUMBER. Standard CDC and dedup pattern.',
    bestUsedFor: ['SCD Type 1 Loads', 'Dedup Pipelines', 'Latest-State Reporting'],
    columnsNeeded: ['CustomerID', 'Date'],
  },
  {
    id: 'sql-quartile-segments',
    name: 'Customer Quartile Segments',
    type: 'sql',
    category: 'Statistical SQL',
    level: 'Advanced',
    formula: `SELECT\n    ${'${custCol}'} AS customer_id,\n    SUM(${'${revCol}'}) AS revenue,\n    NTILE(4) OVER (ORDER BY SUM(${'${revCol}'}) DESC) AS quartile\nFROM ${'${tableName}'}\nGROUP BY ${'${custCol}'};`,
    explanation: 'Splits customers into four equal revenue tiers via NTILE for tiered service models.',
    bestUsedFor: ['Customer Tiering', 'Service Level Agreements', 'Loyalty Programs'],
    columnsNeeded: ['CustomerID', 'Revenue'],
  },
  {
    id: 'sql-pareto-cumulative',
    name: 'Pareto Cumulative Share',
    type: 'sql',
    category: 'Statistical SQL',
    level: 'Expert',
    formula: `WITH ranked AS (\n    SELECT\n        ${'${prodCol}'} AS product,\n        SUM(${'${revCol}'}) AS revenue\n    FROM ${'${tableName}'}\n    GROUP BY ${'${prodCol}'}\n),\ncumulative AS (\n    SELECT\n        product,\n        revenue,\n        SUM(revenue) OVER (ORDER BY revenue DESC) AS cum_revenue,\n        SUM(revenue) OVER () AS total_revenue\n    FROM ranked\n)\nSELECT\n    product,\n    revenue,\n    ROUND(100.0 * cum_revenue / total_revenue, 2) AS cumulative_pct,\n    CASE WHEN cum_revenue / total_revenue <= 0.80 THEN 'A'\n         WHEN cum_revenue / total_revenue <= 0.95 THEN 'B'\n         ELSE 'C' END AS abc_class\nFROM cumulative\nORDER BY revenue DESC;`,
    explanation: 'Ranks products by revenue and classifies them into A/B/C tiers based on cumulative contribution. Foundation for SKU rationalization.',
    bestUsedFor: ['SKU Rationalization', 'Inventory Planning', 'Account Concentration'],
    columnsNeeded: ['Product', 'Revenue'],
  },
  {
    id: 'sql-mom-growth',
    name: 'Month-over-Month Growth %',
    type: 'sql',
    category: 'Time Series Analysis',
    level: 'Advanced',
    formula: `WITH monthly AS (\n    SELECT\n        DATE_TRUNC('month', ${'${dateCol}'}) AS month,\n        SUM(${'${revCol}'}) AS revenue\n    FROM ${'${tableName}'}\n    GROUP BY 1\n)\nSELECT\n    month,\n    revenue,\n    LAG(revenue) OVER (ORDER BY month) AS prev_month,\n    ROUND(100.0 * (revenue - LAG(revenue) OVER (ORDER BY month))\n          / NULLIF(LAG(revenue) OVER (ORDER BY month), 0), 2) AS mom_pct\nFROM monthly;`,
    explanation: 'Aggregates monthly revenue and compares to the prior month using LAG. Replaces brittle self-joins.',
    bestUsedFor: ['Monthly Business Reviews', 'Growth Analytics', 'Investor Reporting'],
    columnsNeeded: ['Date', 'Revenue'],
  },
  {
    id: 'sql-yoy-by-month',
    name: 'YoY Growth per Month',
    type: 'sql',
    category: 'Time Series Analysis',
    level: 'Expert',
    formula: `WITH monthly AS (\n    SELECT\n        DATE_TRUNC('month', ${'${dateCol}'}) AS month,\n        SUM(${'${revCol}'}) AS revenue\n    FROM ${'${tableName}'}\n    GROUP BY 1\n)\nSELECT\n    month,\n    revenue,\n    LAG(revenue, 12) OVER (ORDER BY month) AS revenue_ly,\n    ROUND(100.0 * (revenue - LAG(revenue, 12) OVER (ORDER BY month))\n          / NULLIF(LAG(revenue, 12) OVER (ORDER BY month), 0), 2) AS yoy_pct\nFROM monthly;`,
    explanation: 'Computes year-over-year growth per month with a 12-row LAG offset. Removes seasonality from comparisons.',
    bestUsedFor: ['Seasonality-Adjusted Reports', 'Annual Reviews', 'Investor KPIs'],
    columnsNeeded: ['Date', 'Revenue'],
  },
  {
    id: 'sql-first-touch-attribution',
    name: 'First-Touch Attribution',
    type: 'sql',
    category: 'Cohort & Funnel Tracking',
    level: 'Expert',
    formula: `WITH first_touch AS (\n    SELECT DISTINCT ON (user_id)\n        user_id,\n        channel AS first_channel,\n        ${'${dateCol}'} AS first_touch_date\n    FROM touchpoints\n    ORDER BY user_id, ${'${dateCol}'} ASC\n)\nSELECT\n    f.first_channel,\n    COUNT(DISTINCT c.${'${custCol}'}) AS converted,\n    SUM(c.${'${revCol}'}) AS attributed_revenue\nFROM first_touch f\nJOIN ${'${tableName}'} c ON c.${'${custCol}'} = f.user_id\nGROUP BY f.first_channel\nORDER BY attributed_revenue DESC;`,
    explanation: 'Attributes converted revenue to the channel that first touched each user using DISTINCT ON. Marketing-mix foundation.',
    bestUsedFor: ['Marketing Attribution', 'Channel ROI', 'Budget Allocation'],
    columnsNeeded: ['user_id', 'channel', 'Date', 'CustomerID', 'Revenue'],
  },
  {
    id: 'sql-zscore-anomaly',
    name: 'Z-Score Anomaly Detector',
    type: 'sql',
    category: 'Statistical SQL',
    level: 'Expert',
    formula: `WITH stats AS (\n    SELECT\n        AVG(${'${revCol}'}) AS mu,\n        STDDEV_POP(${'${revCol}'}) AS sigma\n    FROM ${'${tableName}'}\n)\nSELECT\n    ${'${dateCol}'} AS day,\n    ${'${revCol}'} AS revenue,\n    ROUND(((${'${revCol}'} - s.mu) / NULLIF(s.sigma, 0))::numeric, 3) AS z_score,\n    CASE WHEN ABS((${'${revCol}'} - s.mu) / NULLIF(s.sigma, 0)) > 2.5 THEN TRUE ELSE FALSE END AS is_anomaly\nFROM ${'${tableName}'}, stats s\nORDER BY day;`,
    explanation: 'Flags rows whose value is more than 2.5 standard deviations from the mean. Lightweight anomaly detection without ML.',
    bestUsedFor: ['Fraud Detection', 'Quality Alerts', 'Outlier Filtering'],
    columnsNeeded: ['Date', 'Revenue'],
  },
  {
    id: 'sql-customer-tenure',
    name: 'Customer Tenure (Days Active)',
    type: 'sql',
    category: 'Window Functions',
    level: 'Intermediate',
    formula: `SELECT\n    ${'${custCol}'} AS customer_id,\n    MIN(${'${dateCol}'}) AS first_order,\n    MAX(${'${dateCol}'}) AS last_order,\n    MAX(${'${dateCol}'}) - MIN(${'${dateCol}'}) AS tenure_days,\n    COUNT(*) AS total_orders\nFROM ${'${tableName}'}\nGROUP BY ${'${custCol}'};`,
    explanation: 'Computes the number of days each customer has been active. Drives lifecycle stage segmentation.',
    bestUsedFor: ['Lifecycle Reporting', 'Loyalty Analysis', 'Onboarding Metrics'],
    columnsNeeded: ['CustomerID', 'Date'],
  },
  {
    id: 'sql-second-purchase',
    name: 'Time to Second Purchase',
    type: 'sql',
    category: 'Cohort & Funnel Tracking',
    level: 'Advanced',
    formula: `WITH ordered AS (\n    SELECT\n        ${'${custCol}'} AS customer_id,\n        ${'${dateCol}'} AS order_date,\n        ROW_NUMBER() OVER (PARTITION BY ${'${custCol}'} ORDER BY ${'${dateCol}'}) AS rn\n    FROM ${'${tableName}'}\n)\nSELECT\n    a.customer_id,\n    a.order_date AS first_order,\n    b.order_date AS second_order,\n    b.order_date - a.order_date AS days_between\nFROM ordered a\nLEFT JOIN ordered b ON a.customer_id = b.customer_id AND b.rn = 2\nWHERE a.rn = 1;`,
    explanation: 'Pairs the first and second order per customer to study repeat-purchase latency. Drives win-back campaigns.',
    bestUsedFor: ['Repeat-Purchase Strategy', 'Win-back Campaigns', 'Activation KPIs'],
    columnsNeeded: ['CustomerID', 'Date'],
  },
  {
    id: 'sql-stddev-segment',
    name: 'Volatility by Segment',
    type: 'sql',
    category: 'Statistical SQL',
    level: 'Advanced',
    formula: `SELECT\n    segment,\n    AVG(${'${revCol}'}) AS mean_revenue,\n    STDDEV_POP(${'${revCol}'}) AS stddev_revenue,\n    STDDEV_POP(${'${revCol}'}) / NULLIF(AVG(${'${revCol}'}), 0) AS coefficient_of_variation\nFROM ${'${tableName}'}\nGROUP BY segment\nORDER BY coefficient_of_variation DESC;`,
    explanation: 'Computes the coefficient of variation per segment to identify the riskiest revenue streams.',
    bestUsedFor: ['Risk Profiling', 'Portfolio Stability', 'Segment Selection'],
    columnsNeeded: ['segment', 'Revenue'],
  },
  {
    id: 'sql-pivot-monthly',
    name: 'Monthly Revenue Pivot',
    type: 'sql',
    category: 'CTEs & Subqueries',
    level: 'Intermediate',
    formula: `SELECT\n    ${'${prodCol}'} AS product,\n    SUM(CASE WHEN EXTRACT(MONTH FROM ${'${dateCol}'}) = 1  THEN ${'${revCol}'} END) AS jan,\n    SUM(CASE WHEN EXTRACT(MONTH FROM ${'${dateCol}'}) = 2  THEN ${'${revCol}'} END) AS feb,\n    SUM(CASE WHEN EXTRACT(MONTH FROM ${'${dateCol}'}) = 3  THEN ${'${revCol}'} END) AS mar,\n    SUM(CASE WHEN EXTRACT(MONTH FROM ${'${dateCol}'}) = 4  THEN ${'${revCol}'} END) AS apr,\n    SUM(${'${revCol}'}) AS total\nFROM ${'${tableName}'}\nGROUP BY ${'${prodCol}'};`,
    explanation: 'Pivots monthly revenue into wide columns with conditional aggregation. Easy export to Excel.',
    bestUsedFor: ['Spreadsheet Exports', 'Monthly Snapshots', 'Quick Reports'],
    columnsNeeded: ['Product', 'Date', 'Revenue'],
  },
  {
    id: 'sql-rolling-customers',
    name: 'Rolling 30-Day Active Customers',
    type: 'sql',
    category: 'Time Series Analysis',
    level: 'Expert',
    formula: `SELECT\n    day,\n    COUNT(DISTINCT ${'${custCol}'}) FILTER (\n        WHERE ${'${dateCol}'} BETWEEN day - INTERVAL '29 days' AND day\n    ) AS rolling_30d_active\nFROM (\n    SELECT generate_series(MIN(${'${dateCol}'})::date, MAX(${'${dateCol}'})::date, '1 day') AS day\n    FROM ${'${tableName}'}\n) d\nLEFT JOIN ${'${tableName}'} t ON t.${'${dateCol}'} BETWEEN day - INTERVAL '29 days' AND day\nGROUP BY day;`,
    explanation: 'Computes rolling 30-day active customer counts via a generated date spine and filtered DISTINCT count.',
    bestUsedFor: ['Engagement KPIs', 'DAU/WAU/MAU', 'Retention Tracking'],
    columnsNeeded: ['CustomerID', 'Date'],
  },
  {
    id: 'sql-cumulative-customers',
    name: 'Cumulative New Customers',
    type: 'sql',
    category: 'Window Functions',
    level: 'Advanced',
    formula: `WITH first_orders AS (\n    SELECT ${'${custCol}'} AS customer_id, MIN(${'${dateCol}'})::date AS first_date\n    FROM ${'${tableName}'}\n    GROUP BY ${'${custCol}'}\n),\ndaily AS (\n    SELECT first_date, COUNT(*) AS new_customers\n    FROM first_orders\n    GROUP BY first_date\n)\nSELECT\n    first_date,\n    new_customers,\n    SUM(new_customers) OVER (ORDER BY first_date) AS cumulative_total\nFROM daily;`,
    explanation: 'Aggregates first-purchase dates and tracks the cumulative customer base over time.',
    bestUsedFor: ['Growth Tracking', 'Investor Charts', 'Lifecycle Reporting'],
    columnsNeeded: ['CustomerID', 'Date'],
  },
  {
    id: 'sql-conditional-rate',
    name: 'Conditional Conversion Rate',
    type: 'sql',
    category: 'Statistical SQL',
    level: 'Intermediate',
    formula: `SELECT\n    channel,\n    COUNT(*) FILTER (WHERE converted = TRUE) AS conversions,\n    COUNT(*) AS total,\n    ROUND(100.0 * COUNT(*) FILTER (WHERE converted = TRUE) / NULLIF(COUNT(*), 0), 2) AS conversion_rate\nFROM ${'${tableName}'}\nGROUP BY channel\nORDER BY conversion_rate DESC;`,
    explanation: 'Uses FILTER to compute clean per-channel conversion rates without nested CASE expressions.',
    bestUsedFor: ['Channel Performance', 'A/B Tests', 'Marketing Reports'],
    columnsNeeded: ['channel', 'converted'],
  },
  {
    id: 'sql-active-users-roll',
    name: 'DAU / WAU / MAU Stack',
    type: 'sql',
    category: 'Time Series Analysis',
    level: 'Expert',
    formula: `SELECT\n    day,\n    COUNT(DISTINCT user_id) FILTER (WHERE event_date = day) AS dau,\n    COUNT(DISTINCT user_id) FILTER (WHERE event_date BETWEEN day - INTERVAL '6 days' AND day) AS wau,\n    COUNT(DISTINCT user_id) FILTER (WHERE event_date BETWEEN day - INTERVAL '29 days' AND day) AS mau\nFROM (\n    SELECT generate_series(MIN(event_date)::date, MAX(event_date)::date, '1 day') AS day\n    FROM events\n) d\nLEFT JOIN events e ON e.event_date BETWEEN day - INTERVAL '29 days' AND day\nGROUP BY day\nORDER BY day;`,
    explanation: 'Builds DAU, WAU, and MAU from one event log via generated date spine and FILTER clauses.',
    bestUsedFor: ['Product Analytics', 'Engagement Reporting', 'Stickiness Ratio'],
    columnsNeeded: ['user_id', 'event_date'],
  },
  {
    id: 'sql-churn-by-cohort',
    name: 'Churn Rate by Cohort',
    type: 'sql',
    category: 'Cohort & Funnel Tracking',
    level: 'Expert',
    formula: `WITH cohorts AS (\n    SELECT ${'${custCol}'} AS customer_id, DATE_TRUNC('month', MIN(${'${dateCol}'})) AS cohort\n    FROM ${'${tableName}'}\n    GROUP BY ${'${custCol}'}\n),\nlast_seen AS (\n    SELECT ${'${custCol}'} AS customer_id, MAX(${'${dateCol}'}) AS last_active\n    FROM ${'${tableName}'}\n    GROUP BY ${'${custCol}'}\n)\nSELECT\n    c.cohort,\n    COUNT(*) AS cohort_size,\n    COUNT(*) FILTER (WHERE l.last_active < CURRENT_DATE - INTERVAL '90 days') AS churned,\n    ROUND(100.0 * COUNT(*) FILTER (WHERE l.last_active < CURRENT_DATE - INTERVAL '90 days') / COUNT(*), 2) AS churn_pct\nFROM cohorts c\nJOIN last_seen l ON l.customer_id = c.customer_id\nGROUP BY c.cohort\nORDER BY c.cohort;`,
    explanation: 'Computes 90-day inactivity churn per cohort to compare retention quality across acquisition months.',
    bestUsedFor: ['Cohort QA', 'Acquisition Quality', 'Retention Benchmarking'],
    columnsNeeded: ['CustomerID', 'Date'],
  },
  {
    id: 'sql-basket-pairs',
    name: 'Market Basket Co-Purchase',
    type: 'sql',
    category: 'CTEs & Subqueries',
    level: 'Expert',
    formula: `WITH pairs AS (\n    SELECT\n        a.${'${prodCol}'} AS product_a,\n        b.${'${prodCol}'} AS product_b,\n        COUNT(DISTINCT a.order_id) AS co_orders\n    FROM ${'${tableName}'} a\n    JOIN ${'${tableName}'} b\n        ON a.order_id = b.order_id\n        AND a.${'${prodCol}'} < b.${'${prodCol}'}\n    GROUP BY a.${'${prodCol}'}, b.${'${prodCol}'}\n)\nSELECT *\nFROM pairs\nWHERE co_orders >= 5\nORDER BY co_orders DESC\nLIMIT 25;`,
    explanation: 'Self-joins orders to find product pairs frequently bought together. Drives cross-sell recommendations.',
    bestUsedFor: ['Cross-Sell Engines', 'Bundle Strategy', 'Merchandising'],
    columnsNeeded: ['Product', 'order_id'],
  },
  {
    id: 'sql-weekly-active',
    name: 'Weekly Stickiness Ratio',
    type: 'sql',
    category: 'Statistical SQL',
    level: 'Advanced',
    formula: `SELECT\n    DATE_TRUNC('week', event_date) AS week,\n    COUNT(DISTINCT user_id) AS wau,\n    COUNT(DISTINCT user_id) FILTER (WHERE event_date::date = DATE_TRUNC('week', event_date)) AS dau_anchor,\n    ROUND(100.0 * COUNT(DISTINCT user_id) FILTER (WHERE event_date::date = DATE_TRUNC('week', event_date))\n          / NULLIF(COUNT(DISTINCT user_id), 0), 2) AS stickiness\nFROM events\nGROUP BY 1;`,
    explanation: 'Computes weekly stickiness as DAU / WAU. Industry-standard product engagement metric.',
    bestUsedFor: ['Product Analytics', 'Engagement KPIs', 'Investor Decks'],
    columnsNeeded: ['user_id', 'event_date'],
  },
  {
    id: 'sql-account-expansion',
    name: 'Account Expansion Revenue',
    type: 'sql',
    category: 'CTEs & Subqueries',
    level: 'Expert',
    formula: `WITH base AS (\n    SELECT ${'${custCol}'} AS customer_id, DATE_TRUNC('quarter', ${'${dateCol}'}) AS qtr, SUM(${'${revCol}'}) AS revenue\n    FROM ${'${tableName}'}\n    GROUP BY 1, 2\n),\ndelta AS (\n    SELECT\n        customer_id, qtr, revenue,\n        LAG(revenue) OVER (PARTITION BY customer_id ORDER BY qtr) AS prev_revenue\n    FROM base\n)\nSELECT\n    qtr,\n    SUM(GREATEST(revenue - prev_revenue, 0)) AS expansion,\n    SUM(GREATEST(prev_revenue - revenue, 0)) AS contraction,\n    SUM(revenue - COALESCE(prev_revenue, 0)) AS net_change\nFROM delta\nGROUP BY qtr\nORDER BY qtr;`,
    explanation: 'Quantifies expansion vs contraction revenue per quarter from existing accounts. Required for NRR diagnostics.',
    bestUsedFor: ['NRR Diagnostics', 'CS Reviews', 'Account Strategy'],
    columnsNeeded: ['CustomerID', 'Date', 'Revenue'],
  },
  {
    id: 'sql-revenue-bands',
    name: 'Revenue Band Histogram',
    type: 'sql',
    category: 'Statistical SQL',
    level: 'Intermediate',
    formula: `SELECT\n    WIDTH_BUCKET(${'${revCol}'}, 0, 100000, 10) AS bucket,\n    COUNT(*) AS customers,\n    MIN(${'${revCol}'}) AS bucket_min,\n    MAX(${'${revCol}'}) AS bucket_max\nFROM ${'${tableName}'}\nGROUP BY bucket\nORDER BY bucket;`,
    explanation: 'Uses WIDTH_BUCKET to histogram customers into 10 equal revenue bands. Powers distribution charts.',
    bestUsedFor: ['Distribution Charts', 'Pricing Analysis', 'Customer Mix'],
    columnsNeeded: ['Revenue'],
  },
  {
    id: 'sql-gap-detect',
    name: 'Gap Detection in Time Series',
    type: 'sql',
    category: 'Time Series Analysis',
    level: 'Expert',
    formula: `WITH ordered AS (\n    SELECT\n        ${'${dateCol}'} AS day,\n        LAG(${'${dateCol}'}) OVER (ORDER BY ${'${dateCol}'}) AS prev_day\n    FROM (SELECT DISTINCT ${'${dateCol}'} FROM ${'${tableName}'}) d\n)\nSELECT\n    prev_day,\n    day,\n    day - prev_day AS gap_days\nFROM ordered\nWHERE day - prev_day > 1\nORDER BY gap_days DESC;`,
    explanation: 'Surfaces missing dates in a series by comparing each row to its predecessor with LAG. Critical for data quality.',
    bestUsedFor: ['Data Quality', 'Audit Reports', 'Pipeline Monitoring'],
    columnsNeeded: ['Date'],
  },
  {
    id: 'sql-aov-by-segment',
    name: 'Average Order Value by Segment',
    type: 'sql',
    category: 'Statistical SQL',
    level: 'Intermediate',
    formula: `SELECT\n    segment,\n    COUNT(DISTINCT order_id) AS orders,\n    SUM(${'${revCol}'}) AS revenue,\n    ROUND(SUM(${'${revCol}'}) / NULLIF(COUNT(DISTINCT order_id), 0), 2) AS aov\nFROM ${'${tableName}'}\nGROUP BY segment\nORDER BY aov DESC;`,
    explanation: 'Computes AOV per segment using distinct orders and total revenue. Standard merchandising KPI.',
    bestUsedFor: ['Merchandising', 'Pricing Tests', 'Segment Reporting'],
    columnsNeeded: ['segment', 'order_id', 'Revenue'],
  },
  {
    id: 'sql-customer-lifecycle-stage',
    name: 'Customer Lifecycle Stage',
    type: 'sql',
    category: 'Cohort & Funnel Tracking',
    level: 'Advanced',
    formula: `SELECT\n    ${'${custCol}'} AS customer_id,\n    MIN(${'${dateCol}'}) AS first_order,\n    MAX(${'${dateCol}'}) AS last_order,\n    CURRENT_DATE - MAX(${'${dateCol}'})::date AS days_since_last,\n    CASE\n        WHEN CURRENT_DATE - MAX(${'${dateCol}'})::date <= 30 THEN 'Active'\n        WHEN CURRENT_DATE - MAX(${'${dateCol}'})::date <= 90 THEN 'At Risk'\n        WHEN CURRENT_DATE - MAX(${'${dateCol}'})::date <= 180 THEN 'Dormant'\n        ELSE 'Churned'\n    END AS lifecycle_stage\nFROM ${'${tableName}'}\nGROUP BY ${'${custCol}'};`,
    explanation: 'Buckets customers into Active / At Risk / Dormant / Churned based on days since last activity.',
    bestUsedFor: ['CRM Workflows', 'Win-back Targeting', 'Health Scoring'],
    columnsNeeded: ['CustomerID', 'Date'],
  },
  {
    id: 'sql-top-products-by-period',
    name: 'Top 5 Products per Quarter',
    type: 'sql',
    category: 'Window Functions',
    level: 'Expert',
    formula: `WITH ranked AS (\n    SELECT\n        DATE_TRUNC('quarter', ${'${dateCol}'}) AS qtr,\n        ${'${prodCol}'} AS product,\n        SUM(${'${revCol}'}) AS revenue,\n        DENSE_RANK() OVER (\n            PARTITION BY DATE_TRUNC('quarter', ${'${dateCol}'})\n            ORDER BY SUM(${'${revCol}'}) DESC\n        ) AS rnk\n    FROM ${'${tableName}'}\n    GROUP BY 1, 2\n)\nSELECT *\nFROM ranked\nWHERE rnk <= 5\nORDER BY qtr, rnk;`,
    explanation: 'Returns the top 5 products per quarter using a partitioned DENSE_RANK. Standard merchandising leaderboard.',
    bestUsedFor: ['Merchandising Reviews', 'QBR Decks', 'Product Strategy'],
    columnsNeeded: ['Date', 'Product', 'Revenue'],
  },
  {
    id: 'sql-correlation',
    name: 'Pearson Correlation',
    type: 'sql',
    category: 'Statistical SQL',
    level: 'Expert',
    formula: `SELECT\n    CORR(spend, ${'${revCol}'}) AS pearson_r,\n    REGR_SLOPE(${'${revCol}'}, spend) AS slope,\n    REGR_INTERCEPT(${'${revCol}'}, spend) AS intercept\nFROM ${'${tableName}'};`,
    explanation: 'Computes Pearson correlation plus regression slope and intercept between marketing spend and revenue.',
    bestUsedFor: ['Marketing Attribution', 'Driver Analysis', 'Statistical Modelling'],
    columnsNeeded: ['spend', 'Revenue'],
  },

  // ───────────────────────── EXCEL (30) ─────────────────────────
  {
    id: 'excel-xlookup-multi',
    name: 'XLOOKUP with Multi-Column Return',
    type: 'excel',
    category: 'Advanced Lookup',
    level: 'Advanced',
    formula: `=XLOOKUP([@CustomerID], Customers[CustomerID], Customers[[Name]:[Tier]], "Not Found", 0)`,
    explanation: 'Returns multiple columns at once for a matched ID without volatile INDEX/MATCH stacks.',
    bestUsedFor: ['Lookup Pipelines', 'Customer Joins', 'Data Enrichment'],
    columnsNeeded: ['CustomerID', 'Customers Table'],
  },
  {
    id: 'excel-xlookup-approx',
    name: 'XLOOKUP Approximate Tier Match',
    type: 'excel',
    category: 'Advanced Lookup',
    level: 'Advanced',
    formula: `=XLOOKUP([@Revenue], Tiers[MinRevenue], Tiers[Label], "Tier 0", -1)`,
    explanation: 'Performs an approximate match on tier thresholds to assign a label. Replaces clunky nested IFs.',
    bestUsedFor: ['Pricing Tiers', 'Commission Bands', 'Loyalty Levels'],
    columnsNeeded: ['Revenue', 'Tiers Table'],
  },
  {
    id: 'excel-index-match-multi',
    name: 'INDEX / MATCH Multi-Criteria',
    type: 'excel',
    category: 'Advanced Lookup',
    level: 'Advanced',
    formula: `=INDEX(Sales[Revenue],\n    MATCH(1,\n        (Sales[Region]=[@Region]) *\n        (Sales[Product]=[@Product]) *\n        (Sales[Month]=[@Month]),\n        0)\n)`,
    explanation: 'Classic two-criteria INDEX/MATCH using boolean multiplication. Works in legacy Excel without dynamic arrays.',
    bestUsedFor: ['Legacy Excel', 'Multi-key Joins', 'Reporting Sheets'],
    columnsNeeded: ['Region', 'Product', 'Month', 'Revenue'],
  },
  {
    id: 'excel-filter-dynamic',
    name: 'FILTER with Multi-Condition',
    type: 'excel',
    category: 'Dynamic Arrays',
    level: 'Advanced',
    formula: `=FILTER(Sales,\n    (Sales[Region]="EMEA") *\n    (Sales[Revenue]>10000),\n    "No matches")`,
    explanation: 'Returns only rows that satisfy both conditions using boolean multiplication. Replaces autofilter copy-paste.',
    bestUsedFor: ['Dynamic Reporting', 'Self-Service Filters', 'Dashboard Tables'],
    columnsNeeded: ['Region', 'Revenue'],
  },
  {
    id: 'excel-unique-sort',
    name: 'UNIQUE + SORT Combo',
    type: 'excel',
    category: 'Dynamic Arrays',
    level: 'Intermediate',
    formula: `=SORT(UNIQUE(Sales[Product]))`,
    explanation: 'Returns a sorted distinct list of products that updates automatically. Powers dropdowns and slicers.',
    bestUsedFor: ['Dropdown Lists', 'Pivot Sources', 'Slicer Inputs'],
    columnsNeeded: ['Product'],
  },
  {
    id: 'excel-let-readability',
    name: 'LET for Readability',
    type: 'excel',
    category: 'Dynamic Arrays',
    level: 'Advanced',
    formula: `=LET(\n    rev, [@Revenue],\n    cost, [@Cost],\n    margin, rev - cost,\n    pct, margin / rev,\n    IF(pct < 0.10, "Low", IF(pct < 0.25, "Healthy", "Premium"))\n)`,
    explanation: 'Defines named variables once and reuses them, dramatically improving formula readability and performance.',
    bestUsedFor: ['Complex Models', 'Reusable Logic', 'Maintenance'],
    columnsNeeded: ['Revenue', 'Cost'],
  },
  {
    id: 'excel-lambda-named',
    name: 'LAMBDA Reusable Function',
    type: 'excel',
    category: 'Dynamic Arrays',
    level: 'Expert',
    formula: `=LAMBDA(rev, cost, IFERROR((rev - cost) / rev, 0))(B2, C2)`,
    explanation: 'Defines an anonymous function for margin calculation and applies it inline. Save in Name Manager for reuse.',
    bestUsedFor: ['Custom Functions', 'Standardised KPIs', 'Reusable Logic'],
    columnsNeeded: ['Revenue', 'Cost'],
  },
  {
    id: 'excel-byrow-aggregate',
    name: 'BYROW Lambda Aggregator',
    type: 'excel',
    category: 'Dynamic Arrays',
    level: 'Expert',
    formula: `=BYROW(Sales[[Q1]:[Q4]], LAMBDA(row, SUM(row)))`,
    explanation: 'Applies a SUM lambda to each row of a quarterly table without dragging formulas. Native dynamic-array aggregator.',
    bestUsedFor: ['Row Aggregations', 'Annualization', 'KPI Builds'],
    columnsNeeded: ['Q1', 'Q2', 'Q3', 'Q4'],
  },
  {
    id: 'excel-cagr',
    name: 'Compound Annual Growth Rate (CAGR)',
    type: 'excel',
    category: 'Financial Formulas',
    level: 'Advanced',
    formula: `=(EndValue / BeginValue) ^ (1 / NumYears) - 1`,
    explanation: 'Standard CAGR formula returning the smooth annual growth rate that links beginning and ending values.',
    bestUsedFor: ['Financial Modeling', 'Investment Analysis', 'Growth Reporting'],
    columnsNeeded: ['BeginValue', 'EndValue', 'NumYears'],
  },
  {
    id: 'excel-npv',
    name: 'Net Present Value (NPV)',
    type: 'excel',
    category: 'Financial Formulas',
    level: 'Advanced',
    formula: `=NPV(DiscountRate, CashFlows) + InitialInvestment`,
    explanation: 'Computes NPV of future cash flows discounted at the WACC and adjusts by initial outlay.',
    bestUsedFor: ['Capital Budgeting', 'Investment Decisions', 'M&A Analysis'],
    columnsNeeded: ['DiscountRate', 'CashFlows', 'InitialInvestment'],
  },
  {
    id: 'excel-irr',
    name: 'Internal Rate of Return (IRR)',
    type: 'excel',
    category: 'Financial Formulas',
    level: 'Advanced',
    formula: `=IRR({-InitialInvestment; CashFlow1; CashFlow2; CashFlow3; CashFlow4})`,
    explanation: 'Returns the discount rate at which NPV equals zero — the project break-even rate.',
    bestUsedFor: ['Investment Decisions', 'Project Selection', 'Return Analysis'],
    columnsNeeded: ['InitialInvestment', 'CashFlows'],
  },
  {
    id: 'excel-wacc',
    name: 'Weighted Average Cost of Capital (WACC)',
    type: 'excel',
    category: 'Financial Formulas',
    level: 'Expert',
    formula: `=(EquityWeight * CostOfEquity) + (DebtWeight * CostOfDebt * (1 - TaxRate))`,
    explanation: 'Blends after-tax cost of debt with cost of equity weighted by capital structure. Foundation for DCF discount rates.',
    bestUsedFor: ['Corporate Finance', 'Valuation Models', 'Capital Decisions'],
    columnsNeeded: ['EquityWeight', 'CostOfEquity', 'DebtWeight', 'CostOfDebt', 'TaxRate'],
  },
  {
    id: 'excel-pmt-loan',
    name: 'Loan Payment (PMT)',
    type: 'excel',
    category: 'Financial Formulas',
    level: 'Intermediate',
    formula: `=PMT(AnnualRate / 12, Years * 12, -LoanAmount)`,
    explanation: 'Computes monthly loan payment given rate, term, and principal. Negative principal returns positive payment.',
    bestUsedFor: ['Loan Modeling', 'Mortgage Analysis', 'Cash Planning'],
    columnsNeeded: ['AnnualRate', 'Years', 'LoanAmount'],
  },
  {
    id: 'excel-fv-savings',
    name: 'Future Value of Savings (FV)',
    type: 'excel',
    category: 'Financial Formulas',
    level: 'Intermediate',
    formula: `=FV(AnnualRate / 12, Years * 12, -MonthlyContribution, -PresentValue)`,
    explanation: 'Projects the future value of a recurring savings plan with compound growth. Goal-planning workhorse.',
    bestUsedFor: ['Savings Plans', 'Retirement Modeling', 'Goal Tracking'],
    columnsNeeded: ['AnnualRate', 'Years', 'MonthlyContribution', 'PresentValue'],
  },
  {
    id: 'excel-sumifs-multi',
    name: 'SUMIFS with Multiple Filters',
    type: 'excel',
    category: 'Array Manipulation',
    level: 'Intermediate',
    formula: `=SUMIFS(Sales[Revenue],\n    Sales[Region], "EMEA",\n    Sales[Year],   2024,\n    Sales[Status], "Closed")`,
    explanation: 'Conditional sum across three criteria. Replaces array CSE formulas with a clean native function.',
    bestUsedFor: ['Filtered KPIs', 'Slicer-driven Sums', 'Compliance Reports'],
    columnsNeeded: ['Region', 'Year', 'Status', 'Revenue'],
  },
  {
    id: 'excel-countifs-multi',
    name: 'COUNTIFS with Date Range',
    type: 'excel',
    category: 'Array Manipulation',
    level: 'Intermediate',
    formula: `=COUNTIFS(Sales[Date], ">="&StartDate,\n          Sales[Date], "<="&EndDate,\n          Sales[Region], [@Region])`,
    explanation: 'Counts rows matching a date range and a region. Powers windowed activity counts.',
    bestUsedFor: ['Activity Counts', 'Period Filtering', 'Region Reporting'],
    columnsNeeded: ['Date', 'Region'],
  },
  {
    id: 'excel-sequence-dates',
    name: 'SEQUENCE Date Spine',
    type: 'excel',
    category: 'Dynamic Arrays',
    level: 'Advanced',
    formula: `=SEQUENCE(EndDate - StartDate + 1, 1, StartDate, 1)`,
    explanation: 'Generates a continuous date spine between two dates. Essential for filling gaps in time-series reporting.',
    bestUsedFor: ['Time-Series Templates', 'Calendar Builders', 'Reporting Frameworks'],
    columnsNeeded: ['StartDate', 'EndDate'],
  },
  {
    id: 'excel-textsplit-parse',
    name: 'TEXTSPLIT Parser',
    type: 'excel',
    category: 'Array Manipulation',
    level: 'Advanced',
    formula: `=TEXTSPLIT([@FullName], " ", , TRUE)`,
    explanation: 'Splits a full name into first / last with one formula. Replaces LEFT/RIGHT/FIND combinations.',
    bestUsedFor: ['Name Cleansing', 'CSV Parsing', 'Data Enrichment'],
    columnsNeeded: ['FullName'],
  },
  {
    id: 'excel-stockhistory',
    name: 'STOCKHISTORY Pull',
    type: 'excel',
    category: 'Financial Formulas',
    level: 'Advanced',
    formula: `=STOCKHISTORY([@Ticker], TODAY()-365, TODAY(), 2, 0, 0, 1)`,
    explanation: 'Returns the past year of monthly closing prices for a ticker. Native data refresh, no add-ins.',
    bestUsedFor: ['Investment Models', 'Portfolio Tracking', 'Market Analysis'],
    columnsNeeded: ['Ticker'],
  },
  {
    id: 'excel-percentile-array',
    name: 'PERCENTILE on Filtered Array',
    type: 'excel',
    category: 'Array Manipulation',
    level: 'Advanced',
    formula: `=PERCENTILE.INC(\n    FILTER(Sales[Revenue], Sales[Region]=[@Region]),\n    0.95\n)`,
    explanation: 'Combines FILTER and PERCENTILE.INC for region-specific 95th percentile thresholds.',
    bestUsedFor: ['Outlier Thresholds', 'SLA Targets', 'Pricing Analysis'],
    columnsNeeded: ['Region', 'Revenue'],
  },
  {
    id: 'excel-iferror-vlookup',
    name: 'IFERROR + XLOOKUP Safety',
    type: 'excel',
    category: 'Advanced Lookup',
    level: 'Intermediate',
    formula: `=IFERROR(XLOOKUP([@SKU], Catalog[SKU], Catalog[Price]), 0)`,
    explanation: 'Wraps a lookup with IFERROR to default to zero when the SKU is missing. Prevents downstream chart breakage.',
    bestUsedFor: ['Robust Reports', 'Chart Inputs', 'Pivot Sources'],
    columnsNeeded: ['SKU', 'Catalog Table'],
  },
  {
    id: 'excel-textjoin-condition',
    name: 'TEXTJOIN with FILTER',
    type: 'excel',
    category: 'Array Manipulation',
    level: 'Advanced',
    formula: `=TEXTJOIN(", ", TRUE,\n    FILTER(Sales[Product], Sales[Customer]=[@Customer])\n)`,
    explanation: 'Concatenates all products purchased by a given customer into one cell. Great for narrative tables.',
    bestUsedFor: ['Customer Profiles', 'Account Summaries', 'Narrative Reports'],
    columnsNeeded: ['Customer', 'Product'],
  },
  {
    id: 'excel-switch-tier',
    name: 'SWITCH Tier Assignment',
    type: 'excel',
    category: 'Array Manipulation',
    level: 'Intermediate',
    formula: `=SWITCH(TRUE,\n    [@Revenue] >= 100000, "Platinum",\n    [@Revenue] >= 50000,  "Gold",\n    [@Revenue] >= 10000,  "Silver",\n    "Bronze"\n)`,
    explanation: 'Cleanly assigns tier labels using SWITCH(TRUE,…) instead of nested IFs.',
    bestUsedFor: ['Loyalty Tiering', 'Account Bands', 'Pricing Levels'],
    columnsNeeded: ['Revenue'],
  },
  {
    id: 'excel-rank-eq',
    name: 'RANK.EQ with COUNTIFS Tiebreak',
    type: 'excel',
    category: 'Array Manipulation',
    level: 'Advanced',
    formula: `=RANK.EQ([@Revenue], Sales[Revenue]) +\n    COUNTIFS(Sales[Revenue], [@Revenue], Sales[Date], "<"&[@Date])`,
    explanation: 'Computes a strict ranking that breaks ties by earlier date. Useful for league tables.',
    bestUsedFor: ['League Tables', 'Sales Leaderboards', 'KPI Rankings'],
    columnsNeeded: ['Revenue', 'Date'],
  },
  {
    id: 'excel-array-sumproduct',
    name: 'SUMPRODUCT Weighted Average',
    type: 'excel',
    category: 'Array Manipulation',
    level: 'Advanced',
    formula: `=SUMPRODUCT(Sales[Price] * Sales[Qty]) / SUM(Sales[Qty])`,
    explanation: 'Computes a quantity-weighted average price across the entire dataset.',
    bestUsedFor: ['Weighted Pricing', 'Mix Analysis', 'Cost Reporting'],
    columnsNeeded: ['Price', 'Qty'],
  },
  {
    id: 'excel-hstack-stack',
    name: 'HSTACK Side-by-Side Tables',
    type: 'excel',
    category: 'Dynamic Arrays',
    level: 'Advanced',
    formula: `=HSTACK(\n    UNIQUE(Sales[Region]),\n    SUMIFS(Sales[Revenue], Sales[Region], UNIQUE(Sales[Region]))\n)`,
    explanation: 'Builds a 2-column dynamic summary table without pivots. Pure formula reporting.',
    bestUsedFor: ['Live Summaries', 'Mini Dashboards', 'Formula-only Reporting'],
    columnsNeeded: ['Region', 'Revenue'],
  },
  {
    id: 'excel-vstack-merge',
    name: 'VSTACK Multi-Sheet Merge',
    type: 'excel',
    category: 'Dynamic Arrays',
    level: 'Advanced',
    formula: `=VSTACK(Jan!A2:E1000, Feb!A2:E1000, Mar!A2:E1000)`,
    explanation: 'Stacks monthly sheets into one consolidated dataset. Replaces Power Query for simple merges.',
    bestUsedFor: ['Sheet Consolidation', 'Reporting Pipelines', 'Quick Aggregations'],
    columnsNeeded: ['Multiple Sheets'],
  },
  {
    id: 'excel-let-margin',
    name: 'LET Multi-Stage Margin',
    type: 'excel',
    category: 'Dynamic Arrays',
    level: 'Expert',
    formula: `=LET(\n    rev,    SUMIFS(Sales[Revenue], Sales[Region], [@Region]),\n    cost,   SUMIFS(Sales[Cost],    Sales[Region], [@Region]),\n    opex,   SUMIFS(Sales[OpEx],    Sales[Region], [@Region]),\n    gp,     rev - cost,\n    ebitda, gp - opex,\n    HSTACK(rev, gp, ebitda, ebitda / rev)\n)`,
    explanation: 'Derives revenue, GP, EBITDA, and margin per region in a single LET. Single-cell P&L row.',
    bestUsedFor: ['Mini P&L', 'Region Reports', 'FP&A Summaries'],
    columnsNeeded: ['Region', 'Revenue', 'Cost', 'OpEx'],
  },
  {
    id: 'excel-groupby-365',
    name: 'GROUPBY Aggregation (M365)',
    type: 'excel',
    category: 'Dynamic Arrays',
    level: 'Expert',
    formula: `=GROUPBY(Sales[[Region]:[Product]], Sales[Revenue], SUM, 3, 0)`,
    explanation: 'Native dynamic-array equivalent of a pivot table grouped by region and product with totals.',
    bestUsedFor: ['Live Pivots', 'Spilled Reports', 'Self-Service Dashboards'],
    columnsNeeded: ['Region', 'Product', 'Revenue'],
  },
  {
    id: 'excel-pivotby-365',
    name: 'PIVOTBY Cross-Tab (M365)',
    type: 'excel',
    category: 'Dynamic Arrays',
    level: 'Expert',
    formula: `=PIVOTBY(Sales[Region], Sales[Quarter], Sales[Revenue], SUM, 3, 0)`,
    explanation: 'Creates a region × quarter cross-tab with row/column totals — a refreshable pivot replacement.',
    bestUsedFor: ['Cross-Tab Reports', 'Pivot Replacement', 'Executive Tables'],
    columnsNeeded: ['Region', 'Quarter', 'Revenue'],
  },
];
